apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dev
spec:
  selector:
    app: nginx
    version: blue  # Initially set to blue
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
